# Generated by Django 4.2 on 2023-05-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('group', models.IntegerField(null=True)),
                ('course', models.IntegerField(null=True)),
            ],
        ),
    ]
